### ISSUE TITLE
matchmaking: Report session scores

### ISSUE THREAD

**Issue by DJKero** [tristan-zander/runback#10]
I've been trying to implement the `/matchmaking report-score` command, in the Interaction Handler I have something like this:

![Screenshot_20221108_153750](https://user-images.githubusercontent.com/2711997/200647937-b9a42a03-87f4-418f-903a-39d6172cded0.png)

But I can't seem to figure out how to get the option values on the process_command function, I tried a lot.
@tristan-zander do you know if I can print the command options from Twilight to the terminal so I can see what it is that I'm getting?

**Comment by tristan-zander** [comment]
Hey @DJKero, are you running into any specific errors that you can display? Discord is pretty finicky with how it expects the options to be formatted.

If you need to dump the data to the terminal, you can use something like the following (as long as it implements `Debug`):
```rust
debug!(format!("{:?}", &my_variable));
```

**Comment by DJKero** [comment]
I thought that the Box<ApplicationCommandData>.command.data.options would return the vector with all the options but it doesn't seem to be the case.
I'll try using the snippet you sent to see what it's returning, thank you!

**Comment by tristan-zander** [comment]
I would encourage you to look at Twilight's API docs and Discord's Developer Docs to see what data is returned in those circumstances.

**Comment by DJKero** [comment]
> I would encourage you to look at Twilight's API docs and Discord's Developer Docs to see what data is returned in those circumstances.

Yeah I've been doing that, sure. But I don't know how to print this stuff yet, I've been doing the rustlings exercises and I'm pretty new to Rust, but I've been loving how it works and wanted to help with this project 👍🏻 

So the data type needs to implement the Debug trait for this snippet to work?

Thank you it worked! (I had WARN instead of DEBUG in log level, had to figure out that lol):
`discord-bot_1  | 2022-11-08T19:26:05.337907Z DEBUG command_handler: discord_bot::interactions::application_commands::matchmaking: [CommandDataOption { focused: false, name: "report-score", value: SubCommand([CommandDataOption { focused: false, name: "wins", value: Integer(3) }, CommandDataOption { focused: false, name: "loses", value: Integer(0) }]) }]`
