### ISSUE TITLE
matchmaking: Add users to a lobby upon joining thread

### ISSUE THREAD

**Issue by tristan-zander** [tristan-zander/runback#12]
# Description
User's shouldn't have to interact with the application commands in order to interact with Runback. Standard operations with Discord should be supported.

When a user interacts with a matchmaking thread, they should be considered a part of that match.

## Outstanding questions
- Should admins be added to a lobby? It would make sense not to have them act as players _if_ they're just there for conflict resolution.

## Acceptance Criteria for Issue Resolution
- When a user joins a public thread, add them to the lobby if it's a matchmaking thread.
- When a user joins a matchmaking thread, make sure any invitations for them are resolved.
- When a user leaves a matchmaking thread, remove them from the matchmaking session (`matchmaking_player_lobby` db model).

**Comment by DJKero** [comment]
I think that the admins shouldn't be added but maybe we can make the bot send an ephemeral? embedded message (one that when it's interacted with it goes away) so it's not an inconvenience for when they're trying to play.

Do you think something like that would be possible? Do you know if the Twilight API has something useful for this?
I mean if there are events to trigger this?

**Comment by tristan-zander** [comment]
@DJKero Yeah, I think we _could_ do something like this. Perhaps we can introduce the idea of having spectators in the lobby? That way, when a user joins a lobby, they can just toggle themselves as a spectator and not worry about being in rotations or anything.

**Comment by tristan-zander** [comment]
Going to push an MVP out the door with _just_ lobbies and a simpler structure, and then we can continue from there.
