### ISSUE TITLE
matchmaking: General Teams Structure

### ISSUE THREAD

**Issue by tristan-zander** [tristan-zander/runback#20]
The proposal for having teams is as follows:
- When a lobby is opened for a team match, group members into teams.
- Each team is given a `Team` model, and each `MatchmakingPlayerLobby` model will point to that team.
- When a user joins a team, they are given access to a temporary role with the team's name.
  - The role will be placed under the specified Runback Admins for the guild.
  - If there are privileged roles placed under the Runback Admins, then there is an opportunity for guild members to edit roles that they previously did not have access to. Such a situation can be prevented by informing guild admins of such a risk and how to prevent it.
- Players report scores for each match using the standard `/report-score` method, but each player can report and verify the scores for their teams.
- When a team match finishes, report the scores to a `TeamMatch` structure and remove all temporary roles.

If there are any issues or enhancements that we can make to this structure, feel free to comment.

**Comment by DJKero** [comment]
I'd add that to challenge another team directly, someone must:

- Create a team (`/matchmaking teams create`) with the options:
  - name (String)
  - game (Game ID)
  - mode (String??)
    - The model should have info about allowed team quantity and size permutations.
      - With this we're allowing for asymmetric games. (e.g. X vs 1 || X vs Y || X vs Y vs Z, etc)

If the options are valid and the command is processed successfully the temporal role is created.

- Add members (`/matchmaking teams add-member`) with the option:
  - member (Discord user)
    - The member in question should be tagged and be able accept or deny the invitation through an embed.
      - When an invited user accepts, we need to check if the team isn't full before adding the member.

When the team is full, the team leader (the one who created the team) must be notified so he can issue challenges:

- Challenge a user directly (`/matchmaking teams challenge-leader`) with the option:
  - leader (Discord user)

- Challenge a team directly (`/matchmaking teams challenge-team`) with the option:
  - team (Discord role)

Both of these options should send embeds with notifications:

- In the case of a challenge to a user, once the user accepts the invitation he must be prompted for his team name by Runback, then the team and the temporal role are created and the user can add members like described above.
  - After the last member needed for the second team accepts the invitation, all users involved should be tagged and prompted to accept or deny the game.
    - Once all the users accept the invitation we create the lobby and we start accepting score reports and such.

- In the case of a challenge to a team, all users involved **except the one that ran the command** should be tagged and prompted to accept or deny the game.
  - - Once all the users accept the invitation we create the lobby and we start accepting score reports and such.

**Comment by DJKero** [comment]
For matchmaking queue we use the same method but we have a command to join the game's game mode queue.

Maybe `/matchmaking teams queue`?

Obviously we need to have timeouts for teams that are not in a queue or haven't challenged any user or team for X amount of time. To remove them from the queue, delete the team role and remove the active team from the user model.

**Comment by tristan-zander** [comment]
Will revisit this later.
