### ISSUE TITLE
Setting up development environment.

### ISSUE THREAD

**Issue by DJKero** [tristan-zander/runback#7]
Hi, I'm having trouble setting up the environment, I read in the DockerFile that I need to manually mount a volume but I don't know how.

This is the error I'm getting right now:

> [USER@fedora runback]$ sudo docker-compose -f docker-compose.development.yml up discord-bot
> [sudo] password for USER: 
> runback_redis_1 is up-to-date
> runback_zookeeper_1 is up-to-date
> runback_db_1 is up-to-date
> runback_kafka_1 is up-to-date
> Recreating runback_discord-bot_1 ... done
> Attaching to runback_discord-bot_1
> discord-bot_1  | error: project root does not exist
> runback_discord-bot_1 exited with code 1

**Comment by DJKero** [comment]
@tristan-zander Yeah no prob! I reinstalled docker following the recommended way of installing it via their repos instead, and figured out I could add to the cargo.toml inside discord-bot, on [package] the key default-run = "discord-bot".

**Comment by tristan-zander** [comment]
Yep, I did the same thing! Let me know if you need anything else. I'll close this issue as soon as I put up a PR to fix it.

**Comment by DJKero** [comment]
How do I create the Postgres DB on the docker container? I tried to set it up with:
`sudo docker container run -e POSTGRES_USER=USER -e POSTGRES_PASSWORD=PW -e POSTGRES_DB=DB_NAME postgres:14`
I don't know if this already handles the initial setup?

Now I need to run the init.sql to create the tables but I don't know how.

And does the bot already have the functionality to read the credentials from the Bot.toml or something?

**Comment by tristan-zander** [comment]
Ah sorry, I forgot to document all of that. I changed things around so you might have to run the migrator manually. 

1. Copy `Bot.example.toml` into `Bot.toml` and set the parameters to connect to your database.
2. If you don't already have a database, create one manually. The `discord-bot` crate has a binary called `migrator` that you can run to set up all the tables and rows for the database. Please read more at https://www.sea-ql.org/SeaORM/docs/migration/running-migration/
3. If you're running in debug mode, also set the key `debug_server_id` in the config to the id of your development server.

And that should get you all set up.

**Comment by tristan-zander** [comment]
@DJKero Instead of using `docker run`, try using `docker exec` into the already running container, or use VSCode's Docker Extension to attach an interactive terminal. That's usually what I do.

**Comment by tristan-zander** [comment]
Configuration is driven by [figment](https://docs.rs/figment/latest/figment/), and is deserialized into [this struct](https://github.com/tristan-zander/runback/blob/main/discord-bot/src/config.rs#L10-L16)

**Comment by DJKero** [comment]
@tristan-zander Thanks! I'm getting an error regarding the migrator feature not being enabled
`discord-bot_1  | Consider enabling them by passing, e.g., `--features="migrator"``

Where am I supposed to pass that parameter? I tried enabling it in the development.Dockerfile but it didn't work.

**Comment by tristan-zander** [comment]
@DJKero That would be a [crate feature](https://doc.rust-lang.org/cargo/reference/features.html), which you can use like the following: `cargo run --features migrator`

**Comment by DJKero** [comment]
Yeah I had to use the default features key because that wasn't working for me on the Dockerfile.

**Comment by tristan-zander** [comment]
If you're having trouble setting up the database, you can set up your database through the pgadmin4 UI by running it with the docker compose `docker-compose -f docker-compose.development.yml up discord-bot pgadmin`.
The default user of the database is "gale" and the default password is "password". You can always connect to that database by placing those credentials in the Bot.toml if you don't want to set one up manually. I believe there's already a `gale` and `postgres` database by default.
You can run the migrator from within docker if you choose to do so, but I prefer to do it on my local machine. The command looks something like this `DATABASE_URL="postgres://gale:password@localhost:5432/runback" cargo run --features migrator --bin migration`. I recognize the naming isn't consistent for that, so I'll change that.
After that, you should be able to start developing. Let me know if you have any more issues.
